### ISSUE TITLE
Provide the ability to read dot env files and entries using PowerShell

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-tools#11]
As a developer, I'd like to use the module reading dotenv files and their values.

Currently the module only provides the ability to set values in a file. It would be nice if we could also read a value.

    Get-EnvFileVariable -Variable "NODE_EXTRA_CA_CERTS" `
        -Path "$PSScriptRoot\src\rendering\.env.local"

**Comment by nickwesselman** [comment]
Released with 10.2 :)

**Comment by jeanfrancoislarente** [comment]
> Released with 10.2 :)

LFG!!
